# Generated by Django 4.1 on 2022-08-30 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='composer',
            new_name='artist',
        ),
    ]
