# Generated by Django 4.1 on 2022-10-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_user_library_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='library_songs',
            field=models.ManyToManyField(blank=True, related_name='user_owners', to='apis.song'),
        ),
    ]
