# Generated by Django 4.1 on 2022-09-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_rename_composer_song_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genius_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
