# Generated by Django 4.1 on 2022-10-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_user_library_songs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='library_songs',
            new_name='songs',
        ),
    ]
