# Generated by Django 4.1 on 2022-09-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_song_genius_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='setlists',
            field=models.ManyToManyField(related_name='setlist_items', to='apis.setlist'),
        ),
    ]
