# Generated by Django 4.1 on 2022-09-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_song_setlists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='setlists',
        ),
        migrations.AddField(
            model_name='setlist',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='setlists', to='apis.song'),
        ),
    ]
