# Generated by Django 4.1 on 2022-09-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_remove_song_setlists_setlist_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlist',
            name='songs',
            field=models.ManyToManyField(related_name='setlists', to='apis.song'),
        ),
    ]
