# Generated by Django 4.1 on 2022-09-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_song_description_song_full_title_song_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('full_title', models.CharField(max_length=200)),
                ('genius_id', models.IntegerField()),
            ],
        ),
    ]
