# Generated by Django 4.1 on 2022-09-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genius_id', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
