# Generated by Django 4.1 on 2022-09-09 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_alter_album_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='artist_name',
        ),
    ]
