# Generated by Django 4.1 on 2022-09-12 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_album_artist_alter_album_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setlist',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
