# Generated by Django 4.1 on 2022-09-12 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_rename_created_at_setlist_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist_name',
        ),
    ]
