# Generated by Django 4.1 on 2022-09-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_remove_song_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
